### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by amitkumarj441**
added KTextEditor link

### CODE REVIEW

**Comment by vkrause** [comment]
Integrated, thanks!

**Comment by amitkumarj441** [comment]
@vkrause Please do check this PR and merge it!

**Comment by vkrause** [comment]
I don't seem to be able to merge or close the PR (probably due to this just being a mirror), I can only cherry pick and push to upstream directly (which I did).

**Comment by dhaumann** [comment]
@vkrause I think the issue is that we are not owners of this repository, right?

**Comment by amitkumarj441** [comment]
Alright @dhaumann !

**Comment by dhaumann** [comment]
This was already merged by Volker - thanks for the contribution.

**Pull request closed without merging**
