### PR TITLE
Agda keywords updated to 2.6.0.

### PR DESCRIPTION
**Pull request by andreasabel**
Agda keywords updated to 2.6.0.

Some new keywords have been added over time...

### CODE REVIEW

**Comment by nibags** [comment]
This is a mirror repository, the correct repository is: https://phabricator.kde.org/source/syntax-highlighting/

I integrated the changes you have made, thanks! -> https://phabricator.kde.org/D27797
I also corrected the highlighting of floating points in Agda, which I noticed when checking the test file.

Regards!

**Comment by andreasabel** [comment]
Thanks a lot @nibags !

**Comment by andreasabel** [comment]
> This is a mirror repository, the correct repository is: https://phabricator.kde.org/source/syntax-highlighting/

Ah, ok.  I was looking for sign whether I am at the correct repo, like whether this is a fork, but couldn't see anything.

Maybe the Readme could point to the correct repository so outsiders like me can now.

Again, thanks for taking care!

**Comment by nibags** [comment]
Misprint: recently this repository has been migrated to GitLab (invent.kde.org): https://invent.kde.org/frameworks/syntax-highlighting

I updated the README file with all the necessary information to collaborate.

**Comment by tsdgeos** [comment]
Thanks for your contribution :)

This repository is a mirror of a KDE repository. This means that developers are not looking at pull requests created in GitHub, so I'm closing this pull request (actually a bot is doing it).
Please see https://community.kde.org/Infrastructure/Github_Mirror for details on how to contribute to this and other KDE projects.

**Pull request closed without merging**
