### PR TITLE
Add Nim syntax

### PR DESCRIPTION
**Pull request by danipozo**
Adds Nim syntax from https://github.com/juancarlospaco/NimKate.

I know this is just a mirror, but the KDE GitLab instance requires signing up, which puts me through a reCAPTCHA I can't even get to work in my browser.

### CODE REVIEW

**Comment by nibags** [comment]
Hi, thanks for the new highlighter.

The XML file is fine, but it has some errors:
- There can be no spaces or delimiters inside `<item>...</item>` in keyword lists.
- In `<comment position="..." />` the value "beforewhitespace" isn't valid. The only possible value is "afterwhitespace".

Also, it's necessary to add a test file.

If there is no problem, I can fix this and upload the file to the repository in GitLab.

**Comment by danipozo** [comment]
> If there is no problem, I can fix this and upload the file to the repository in GitLab.

This would be great, thank you.

**Comment by nibags** [comment]
Are you not the original author of the XML file?

I got a test file from the documentation and there are Nim features that aren't present in the highlighter (like strings with three quotes and raw-strings). If it doesn't matter I will add what is missing.

**Comment by danipozo** [comment]
> Are you not the original author of the XML file?

No.

> I got a test file from the documentation and there are Nim features that aren't present in the highlighter (like strings with three quotes and raw-strings). If it doesn't matter I will add what is missing.

Might be a bit outdated, yes. Of course, it would be very nice.

**Comment by nibags** [comment]
It's already up: https://invent.kde.org/frameworks/syntax-highlighting/-/merge_requests/20

I don't have permissions to close pull requests, please do it yourself.

**Pull request closed without merging**
