### PR TITLE
Support for systemd unit files

### PR DESCRIPTION
**Pull request by VasiliPupkin256**

### CODE REVIEW

**Comment by tosky** [comment]
Please note that the KDE project doesn't use github, which is just a mirror. More information on how to contribute are available here: https://community.kde.org/Get_Involved/development

**Comment by VasiliPupkin256** [comment]
They leave repository open for pull requests and I am not going to register on their website just for this single patch. May be someone who is visiting this repo would merge it their under his name one day.

**Comment by tosky** [comment]
Unfortunately we (KDE) can't close the pull request without disabling other parts needed for the mirroring. We have a bot that close the PR automatically, but due to change to the API it broke some time ago and it seems we are missing the people with the knowledge to fix it ( see also https://marc.info/?l=kde-devel&m=160880415529294&w=2).
So this is more likely to be closed at some point without people looking at it, unfortunately.

**Comment by nicolas17** [comment]
> They leave repository open for pull requests

GitLab doesn't support closing the repository for pull requests.

**Comment by tsdgeos** [comment]
Thanks for your contribution :)

This repository is a mirror of a KDE repository. This means that developers are not looking at pull requests created in GitHub, so I'm closing this pull request (actually a bot is doing it).
Please see https://community.kde.org/Infrastructure/Github_Mirror for details on how to contribute to this and other KDE projects.

**Pull request closed without merging**
