### PR TITLE
Adding file extensions to PHP syntax

### PR DESCRIPTION
**Pull request by Tectu**
For some reason that is unknown to me the PHP syntax file lacks the known file extensions list.

### CODE REVIEW

**Comment by dhaumann** [comment]
Does this really work? It says hidden="true" and I no file extensions at all. The reason is that there is a script that generates the php-php.xml file or similar. In this script, the extensions should be added, iirc...

**Comment by dhaumann** [comment]
See here: https://github.com/KDE/syntax-highlighting/blob/master/data/generators/generate-php.pl#L40

Does your patch fix a particular bug?

**Comment by Tectu** [comment]
This is interesting, I didn't notice the generator script until you pointed it out.
I'm not sure if maybe the generated php.xml file is outdated or whether there's a bug in the generator or the generator script as I didn't use the generator at all. I'm just straight using the XML files in the `data/syntax` directory.

In my case `Repository::definitionForFileName()` didn't return the PHP `Definition` for a file with a `*.php` extension. This patch made this problem go away, it now returns the proper PHP `Definition` object.
So whether or not this is the correct way of fixing this or whether or not I'm the only one experiencing this is something I cannot judge due to lack of knowledge of the system - I'm completely new to this.

**Comment by dhaumann** [comment]
OK, in that case this patch is not correct, and the generator script already includes your extensions. The script is called three times here: 
https://github.com/KDE/syntax-highlighting/blob/master/data/CMakeLists.txt#L18

Also note, that all xml files are compiled into the library as Qt resource file. This speeds up the startup of processes.

The generated files are Btw included here:
https://kate-editor.org/syntax/
This location is used to download updates.

I will close this pull request without merging. When compiling the library, look into the build folder. There you will rind the additional auto generated files you are looking for.

Do you have any other questions? :)

**Comment by dhaumann** [comment]
Just to add this again: you should not need to ship any xml files, since everything is compiled into the binary.

**Pull request closed without merging**
