### PR TITLE
Add syntax highlighting for MIB files

### PR DESCRIPTION
**Pull request by JaapKeuter**

### CODE REVIEW

**Comment by tsdgeos** [comment]
Thanks for your contribution :smiley:

This repository is a mirror of a KDE repository. This means that developers are not looking at pull requests created in GitHub, so I'm closing this pull request (actually a bot is doing it).
Please see https://community.kde.org/Infrastructure/Github_Mirror for details on how to contribute to this and other KDE projects.

**Comment by dhaumann** [comment]
Hi, thanks for your pull request. Could you change the license to MIT? This is the preferred license for new highlighting files.

Also, can you please add a test file to the Autotest/input folder, so that we have a nice unit test? Preferably also under MIT license.

**Comment by JaapKeuter** [comment]
I am looking at the KDE submission process first. I will take your requests in consideration before creating a pull request.

**Comment by dhaumann** [comment]
Ok, thanks!

**Pull request closed without merging**
