### PR TITLE
doxygen configuration syntax (aka Doxyfile)

### PR DESCRIPTION
**Pull request by amigo421**

### CODE REVIEW

**Comment by amigo421** [comment]
hey, seems , the quickest way to contribute is a phabricator.kde.org
isn't it? 
unfortuantelly , it works unstable, all attempt to register produce the error:

> The given validation could not be confirmed, please contact the site administrator.

and report about the error I can after the login only ...


so I've submitted my PR here, please review

**Comment by dhaumann** [comment]
You need to create an account on identity.kde.org.

And did you see: https://phabricator.kde.org/D5338

**Comment by amigo421** [comment]
Okay, I'll try.
Yes, just saw this, but my version is more advanced :)

**Comment by tsdgeos** [comment]
Thanks for your contribution :)

This repository is a mirror a KDE repository. For this reason we can't accept contributions through Github. Please see https://community.kde.org/Infrastructure/Github_Mirror for details on how to contribute to this and other KDE projects.

**Comment by dhaumann** [comment]
@tsdgeos I would have preferred to close this when the issue is really resolved. Since this patch is probably better than the one on Phab. ;)

@kfunk can you take care of this?

**Comment by tsdgeos** [comment]
@dhaumann It was discussed and agreed in kde-devel that its better to have a bot (that's what above comment is) that closes pull requests and tells people to go to somewhere people will actually have a look at than having hundred open requests that [almost] no one was looking at.

**Pull request closed without merging**
