### PR TITLE
Add "say" function

### PR DESCRIPTION
**Pull request by caribe**
Modern Perl includes the really common "say" function.

https://perldoc.perl.org/functions/say.html

### CODE REVIEW

**Comment by tsdgeos** [comment]
Thanks for your contribution :smiley:

This repository is a mirror of a KDE repository. This means that developers are not looking at pull requests created in GitHub, so I'm closing this pull request (actually a bot is doing it).
Please see https://community.kde.org/Infrastructure/Github_Mirror for details on how to contribute to this and other KDE projects.

**Comment by dhaumann** [comment]
I will integrate this change later - thanks!

**Comment by dhaumann** [comment]
@caribe: With modern perl, do you mean perl6? I am asking since perl6.xml already includes the keyword 'say'. So my question would be: Does belong 'say' also into perl5?

**Comment by dhaumann** [comment]
Based on https://perldoc.perl.org/functions/say.html I have committed this now: e8e098bd9f28c698a73d081b20e4c46444e6a50f

**Pull request closed without merging**
