### PR TITLE
awk: add gawk extension keywords

### PR DESCRIPTION
**Pull request by jannick0**
The additional keyword cover more keywords of gawk, version 4.2.

### CODE REVIEW

**Comment by tsdgeos** [comment]
Thanks for your contribution :smiley:

This repository is a mirror of a KDE repository. This means that developers are not looking at pull requests created in GitHub, so I'm closing this pull request (actually a bot is doing it).
Please see https://community.kde.org/Infrastructure/Github_Mirror for details on how to contribute to this and other KDE projects.

**Comment by dhaumann** [comment]
Either you provide a patch on phabricator.kde.org, or I'll take care of this later.

**Comment by jannick0** [comment]
I posted a patch [here](https://bugs.kde.org/show_bug.cgi?id=389590) - which might be the wrong place either - after I learnt that github is not the right one. Please give me shout if you want me to post it on phabricator.kde.org again.

**Comment by dhaumann** [comment]
Done, thanks for the patch: 0f75a3659b3c277cc624b7f4416954ffd961f272

**Pull request closed without merging**
