### PR TITLE
Update Logtalk language syntax support

### PR DESCRIPTION
**Pull request by pmoura**

### CODE REVIEW

**Comment by tsdgeos** [comment]
Thanks for your contribution :smiley:

This repository is a mirror of a KDE repository. This means that developers are not looking at pull requests created in GitHub, so I'm closing this pull request (actually a bot is doing it).
Please see https://community.kde.org/Infrastructure/Github_Mirror for details on how to contribute to this and other KDE projects.

**Comment by pmoura** [comment]
It would be wise then to state that in this repo readme so that people that want to contribute don't waste their time forking, cloning, branching, committing, pushing, and creating useless pull requests!

**Comment by dhaumann** [comment]
Agreed. However, I would have taken care here as well, if you hadn't posted it on phabricator.

**Comment by pmoura** [comment]
Thanks. Please let me know if the changes at phabricator need any fixing before merging. Should I add you as a reviewer there?

**Comment by dhaumann** [comment]
Let's continue the discussion there.

**Pull request closed without merging**
